language: python
sudo: false
python:
    - 3.8
sudo: false
install:
    - pip install ipython nose requests codecov pytest coverage pytest-cover
    - python setup.py develop
script:
    - python runtests.py

after_success:
  - codecov
